import { useEffect, useMemo, useRef, useState } from "react";
import * as echarts from "echarts/core";
import { EffectScatterChart, LinesChart, MapChart } from "echarts/charts";
import { GeoComponent, TitleComponent, TooltipComponent } from "echarts/components";
import { CanvasRenderer } from "echarts/renderers";
import { ORIGIN } from "../lib/tripStore.js";
echarts.use([GeoComponent, TitleComponent, TooltipComponent, EffectScatterChart, LinesChart, MapChart, CanvasRenderer]);

export default function MapDashboard({ records }) {
  const chartRef = useRef(null); const instanceRef = useRef(null); const [state, setState] = useState("loading"); const [playIndex, setPlayIndex] = useState(-1); const [playing, setPlaying] = useState(false);
  const timeline = useMemo(() => [...records].sort((a, b) => a.date.localeCompare(b.date)), [records]); const active = playIndex < 0 ? records : timeline.slice(0, playIndex + 1); const current = timeline[playIndex];
  const stats = [{ value: active.length, label: "地点记录" }, { value: new Set(active.map((x) => x.region)).size, label: "覆盖区域" }, { value: active.reduce((s, x) => s + x.days, 0), label: "累计天数" }, { value: playIndex < 0 ? timeline.length : playIndex + 1, label: "已回放" }];
  useEffect(() => { fetch("/maps/china.geo.json").then((r) => { if (!r.ok) throw Error(); return r.json(); }).then((map) => { echarts.registerMap("china", map); setState("ready"); }).catch(() => setState("error")); }, []);
  useEffect(() => { if (state !== "ready" || !chartRef.current) return; const chart = instanceRef.current || echarts.init(chartRef.current); instanceRef.current = chart; chart.setOption({ backgroundColor: "transparent", title: { text: "足迹地图", subtext: current ? `${current.date} · ${current.city} · ${current.days} 天` : "全部记录", left: "center", top: 12, textStyle: { color: "#1d1d1f", fontSize: 18, fontWeight: 700 }, subtextStyle: { color: "#86868b", fontSize: 12 } }, tooltip: { trigger: "item", backgroundColor: "rgba(255,255,255,.96)", borderColor: "#e5e5e7", borderWidth: 1, textStyle: { color: "#1d1d1f" }, formatter: (p) => p.data?.record ? `${p.data.record.city}<br/>${p.data.record.region} · ${p.data.record.date}<br/>停留 ${p.data.record.days} 天` : p.name }, geo: { map: "china", roam: true, zoom: 1.15, itemStyle: { areaColor: "#f3f3f5", borderColor: "#d5d5da" }, emphasis: { itemStyle: { areaColor: "#e7e7eb" } } }, series: [{ type: "effectScatter", coordinateSystem: "geo", rippleEffect: { brushType: "stroke", scale: 4 }, symbolSize: (v) => 8 + v[2] * 3, itemStyle: { color: "#e97876" }, label: { show: true, position: "right", formatter: "{b}", color: "#3a3a3c", fontSize: 10 }, data: active.map((x) => ({ name: x.city, value: [...x.coord, x.days], record: x })) }, { type: "lines", coordinateSystem: "geo", effect: { show: true, period: 4, symbol: "arrow", symbolSize: 6, color: "#e97876" }, lineStyle: { color: "#e97876", width: 1.2, opacity: .5, curveness: .25 }, data: active.map((x) => ({ coords: [ORIGIN.coord, x.coord] })) }, { type: "effectScatter", coordinateSystem: "geo", symbolSize: 12, itemStyle: { color: "#c75c5b" }, label: { show: true, position: "top", formatter: ORIGIN.name, color: "#a94f4d" }, data: [{ name: ORIGIN.name, value: ORIGIN.coord }] }] }, true); const resize = () => chart.resize(); addEventListener("resize", resize); return () => removeEventListener("resize", resize); }, [active, current, state]);
  useEffect(() => () => instanceRef.current?.dispose(), []); useEffect(() => { if (!playing) return; const timer = setInterval(() => setPlayIndex((v) => { if (v >= timeline.length - 1) { setPlaying(false); return v; } return v + 1; }), 1400); return () => clearInterval(timer); }, [playing, timeline.length]);
  return <><section className="stats">{stats.map((x) => <div className="stat" key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</section><section className="map-wrap" aria-busy={state === "loading"}>{state === "loading" && <div className="status">正在打开离线地图…</div>}{state === "error" && <div className="status error">本地地图文件不可用，请重新安装应用。</div>}<div ref={chartRef} className="chart" hidden={state !== "ready"} /></section><section className="controls"><button className="button primary" onClick={() => { if (playIndex < 0 || playIndex >= timeline.length - 1) setPlayIndex(0); setPlaying(true); }} disabled={!timeline.length}>{playing ? "回放中" : playIndex >= 0 ? "继续回放" : "路线回放"}</button><button className="button secondary" onClick={() => setPlaying(false)} disabled={!playing}>暂停</button><button className="button secondary" onClick={() => { setPlaying(false); setPlayIndex(-1); }}>显示全部</button></section>{current && <div className="progress" aria-live="polite"><span>{current.date}　{current.city}　{current.days} 天</span><i style={{ "--progress": `${((playIndex + 1) / timeline.length) * 100}%` }} /></div>}<section className="footprints"><h2>已收集地点</h2><div>{records.length ? records.map((x) => <span className={`chip${active.includes(x) ? " is-active" : ""}`} key={x.id}>{x.city} <b>{x.date}</b></span>) : <p className="empty">暂未收集地点，去手机采集页添加第一条记录。</p>}</div></section></>;
}
