import { useEffect, useMemo, useRef, useState } from "react";
import * as echarts from "echarts/core";
import { EffectScatterChart, LinesChart, MapChart } from "echarts/charts";
import { GeoComponent, TitleComponent, TooltipComponent } from "echarts/components";
import { CanvasRenderer } from "echarts/renderers";
import { ORIGIN } from "../lib/tripStore.js";
import { ACHIEVEMENTS, CITY_GUIDES, achievementFor, nextAchievementFor } from "../lib/cityGuide.js";
echarts.use([GeoComponent, TitleComponent, TooltipComponent, EffectScatterChart, LinesChart, MapChart, CanvasRenderer]);

export default function MapDashboard({ records }) {
  const chartRef = useRef(null); const instanceRef = useRef(null); const [state, setState] = useState("loading"); const [playIndex, setPlayIndex] = useState(-1); const [playing, setPlaying] = useState(false);
  const timeline = useMemo(() => [...records].sort((a, b) => a.date.localeCompare(b.date)), [records]); const active = playIndex < 0 ? records : timeline.slice(0, playIndex + 1); const current = timeline[playIndex]; const unlockedCities = useMemo(() => [...new Set(records.map((item) => item.city.trim()).filter(Boolean))], [records]); const currentAchievement = achievementFor(unlockedCities.length); const nextAchievement = nextAchievementFor(unlockedCities.length); const cityGuides = unlockedCities.map((city) => ({ city, guide: CITY_GUIDES[city] })).filter((item) => item.guide);
  const stats = [{ value: active.length, label: "雪糕球" }, { value: new Set(active.map((x) => x.region)).size, label: "解锁区域" }, { value: active.reduce((s, x) => s + x.days, 0), label: "旅行天数" }, { value: playIndex < 0 ? timeline.length : playIndex + 1, label: "回味进度" }];
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}maps/china.geo.json`).then((r) => { if (!r.ok) throw Error(); return r.json(); }).then((map) => { echarts.registerMap("china", map); setState("ready"); }).catch(() => setState("error")); }, []);
  useEffect(() => { if (state !== "ready" || !chartRef.current) return; const chart = instanceRef.current || echarts.init(chartRef.current); instanceRef.current = chart; chart.setOption({ backgroundColor: "transparent", title: { text: "雪糕旅程地图", subtext: current ? `${current.date} · ${current.city} · ${current.days} 天` : "虚构示例路线 · 不代表真实行程", left: "center", top: 12, textStyle: { color: "#1d1d1f", fontSize: 18, fontWeight: 700 }, subtextStyle: { color: "#86868b", fontSize: 12 } }, tooltip: { trigger: "item", backgroundColor: "rgba(255,255,255,.96)", borderColor: "#e5e5e7", borderWidth: 1, textStyle: { color: "#1d1d1f" }, formatter: (p) => p.data?.record ? `${p.data.record.city}<br/>${p.data.record.region} · ${p.data.record.date}<br/>停留 ${p.data.record.days} 天` : p.name }, geo: { map: "china", roam: true, zoom: 1.15, itemStyle: { areaColor: "#f3f3f5", borderColor: "#d5d5da" }, emphasis: { itemStyle: { areaColor: "#e7e7eb" } } }, series: [{ type: "effectScatter", coordinateSystem: "geo", rippleEffect: { brushType: "stroke", scale: 4 }, symbolSize: (v) => 8 + v[2] * 3, itemStyle: { color: "#e97876" }, label: { show: true, position: "right", formatter: "{b}", color: "#3a3a3c", fontSize: 10 }, data: active.map((x) => ({ name: x.city, value: [...x.coord, x.days], record: x })) }, { type: "lines", coordinateSystem: "geo", effect: { show: true, period: 4, symbol: "arrow", symbolSize: 6, color: "#e97876" }, lineStyle: { color: "#e97876", width: 1.2, opacity: .5, curveness: .25 }, data: active.map((x) => ({ coords: [ORIGIN.coord, x.coord] })) }, { type: "effectScatter", coordinateSystem: "geo", symbolSize: 12, itemStyle: { color: "#c75c5b" }, label: { show: true, position: "top", formatter: ORIGIN.name, color: "#a94f4d" }, data: [{ name: ORIGIN.name, value: ORIGIN.coord }] }] }, true); const resize = () => chart.resize(); addEventListener("resize", resize); return () => removeEventListener("resize", resize); }, [active, current, state]);
  useEffect(() => () => instanceRef.current?.dispose(), []); useEffect(() => { if (!playing) return; const timer = setInterval(() => setPlayIndex((v) => { if (v >= timeline.length - 1) { setPlaying(false); return v; } return v + 1; }), 1400); return () => clearInterval(timer); }, [playing, timeline.length]);
  return <><section className="stats">{stats.map((x) => <div className="stat" key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</section><section className="map-wrap" aria-busy={state === "loading"}>{state === "loading" && <div className="status">正在打开雪糕地图…</div>}{state === "error" && <div className="status error">雪糕地图没有准备好，请重新安装应用。</div>}<div ref={chartRef} className="chart" hidden={state !== "ready"} /></section><section className="controls"><button className="button primary" onClick={() => { if (playIndex < 0 || playIndex >= timeline.length - 1) setPlayIndex(0); setPlaying(true); }} disabled={!timeline.length}>{playing ? "正在回味" : playIndex >= 0 ? "继续回味" : "回味旅程"}</button><button className="button secondary" onClick={() => setPlaying(false)} disabled={!playing}>先放一放</button><button className="button secondary" onClick={() => { setPlaying(false); setPlayIndex(-1); }}>看看全部</button></section>{current && <div className="progress" aria-live="polite"><span>{current.date}　{current.city}　{current.days} 天</span><i style={{ "--progress": `${((playIndex + 1) / timeline.length) * 100}%` }} /></div>}<section className="achievement" aria-label="城市解锁成就"><div className="achievement-main"><span className="achievement-icon">{currentAchievement?.icon || "🍦"}</span><div><p>已解锁 {unlockedCities.length} 座城市</p><h2>{currentAchievement?.title || "第一口，先出发"}</h2><span>{currentAchievement?.note || "记录第一座城市即可解锁称号。"}</span></div></div>{nextAchievement ? <div className="achievement-next"><span>距离「{nextAchievement.title}」还差 {nextAchievement.min - unlockedCities.length} 座</span><i><b style={{ width: `${Math.min(100, (unlockedCities.length / nextAchievement.min) * 100)}%` }} /></i></div> : <p className="achievement-complete">全部称号已点亮，继续为你的雪糕柜添新口味吧。</p>}<div className="achievement-badges">{ACHIEVEMENTS.map((item) => <span className={unlockedCities.length >= item.min ? "is-unlocked" : ""} key={item.title} title={`${item.min} 座城市解锁`}>{item.icon}<b>{item.title}</b></span>)}</div></section><section className="city-discoveries"><div className="section-heading"><div><p>LOCAL FLAVOURS</p><h2>解锁城市的当地灵感</h2></div><span>出发前以官方信息为准</span></div>{cityGuides.length ? <div className="city-guide-grid">{cityGuides.map(({ city, guide }) => <article className="city-guide" key={city}><div className="city-guide-title"><div><span>{guide.tone}</span><h3>{city}</h3></div><i>🍨</i></div><div className="guide-pairs"><p><b>🍜 吃什么</b>{guide.foods.join(" · ")}</p><p><b>📍 去哪里</b>{guide.sights.join(" · ")}</p></div><p className="guide-tip">{guide.tip}</p><a href={guide.source.url} target="_blank" rel="noreferrer">{guide.source.label} ↗</a></article>)}</div> : <p className="empty">解锁城市后，这里会出现一张当地灵感卡。</p>}</section><section className="footprints"><h2>我的雪糕柜</h2><div>{records.length ? records.map((x) => <span className={`chip${active.includes(x) ? " is-active" : ""}`} key={x.id}>🍨 {x.city} <b>{x.date}</b></span>) : <p className="empty">雪糕柜还是空的，去加第一球旅程吧。</p>}</div></section></>;
}
