import { useEffect, useRef, useState } from "react";
import { parseTicketText, recognizeTicket } from "../lib/ticketOcr.js";
import { addTripRecord } from "../lib/tripStore.js";
import { findPlace } from "../lib/placeCatalog.js";
import PlacePicker from "../components/PlacePicker.jsx";

const blank = () => ({ province: "", city: "", placeId: "", date: "", days: 1, ticketType: "", ticketNumber: "" });
export default function TicketScanner({ onSaved }) {
  const inputRef = useRef(null); const [preview, setPreview] = useState(""); const [result, setResult] = useState(null); const [form, setForm] = useState(blank); const [text, setText] = useState(""); const [status, setStatus] = useState("");
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  const applyParsed = (parsed) => { setResult(parsed); setForm((value) => ({ ...value, date: parsed.date || value.date, ticketType: parsed.type || value.ticketType, ticketNumber: parsed.ticketNumber || value.ticketNumber })); setStatus(parsed.arrival ? `识别到目的地候选「${parsed.arrival}」，请在下方选择准确的省、市、区县。` : "未能可靠提取地点，请在下方选择。 "); };
  const choose = async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setStatus("图片请控制在 10MB 以内。"); return; } if (preview) URL.revokeObjectURL(preview); setPreview(URL.createObjectURL(file)); setResult(null); setStatus("正在准备本地识别…"); try { applyParsed(await recognizeTicket(file, setStatus)); } catch { setStatus("识别失败，请换一张清晰截图，或改为粘贴文字。 "); } event.target.value = ""; };
  const parseText = () => { if (!text.trim()) return setStatus("请先粘贴车票、机票或行程单中的文字。"); applyParsed(parseTicketText(text.slice(0, 20000))); };
  const save = (event) => { event.preventDefault(); const place = findPlace(form.placeId); if (!place || !form.date) return setStatus("请确认日期，并选择准确的省、市、区县。 "); try { onSaved(addTripRecord({ city: place.city.replace("市", ""), region: `${place.province}${place.city}${place.district}`, coord: place.coord, date: form.date, days: form.days, ticketType: form.ticketType, ticketNumber: form.ticketNumber, placeId: place.id })); setStatus("行程已保存到本地足迹。 "); setResult(null); setText(""); setForm(blank()); if (preview) URL.revokeObjectURL(preview); setPreview(""); } catch (error) { setStatus(error.message); } };
  return <section className="scanner"><div className="collector-intro"><p className="eyebrow">TICKET SCOOP</p><h2>扫一扫，挖一球回忆</h2><p>图片与文字均只在当前设备解析，不会上传；请先遮挡姓名、证件号和订单号。</p></div><button className="scan-drop" onClick={() => inputRef.current?.click()}><span>🍦</span><strong>选择一张旅程票据</strong><small>相册、相机、PNG、JPG、WEBP、HEIC，最多 10MB</small></button><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp,image/heic,image/heif" capture="environment" hidden onChange={choose} />{preview && <img className="ticket-preview" src={preview} alt="待识别票据截图" />}{status && <p className="form-message" role="status">{status}</p>}{result && <details className="ocr-text"><summary>看看识别到了什么</summary><p>{result.rawText || "这张票据有点糊，再试一次吧"}</p></details>}<div className="text-import"><label>或粘贴行程文字<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="粘贴车票、机票、短信或行程单文字" maxLength="20000" /></label><button className="button secondary" type="button" onClick={parseText}>解析这段文字</button></div><form onSubmit={save} className="ocr-form"><div className="form-grid"><label>票据类型<input name="ticketType" value={form.ticketType} onChange={(event) => setForm((value) => ({ ...value, ticketType: event.target.value }))} placeholder="机票或火车票" /></label><label>航班 / 车次<input name="ticketNumber" value={form.ticketNumber} onChange={(event) => setForm((value) => ({ ...value, ticketNumber: event.target.value }))} placeholder="例如 CA1234" /></label></div><PlacePicker value={form} onChange={setForm} compact /><div className="form-grid"><label>日期<input name="date" type="date" value={form.date} onChange={(event) => setForm((value) => ({ ...value, date: event.target.value }))} /></label><label>停留天数<input name="days" type="number" min="1" max="365" value={form.days} onChange={(event) => setForm((value) => ({ ...value, days: event.target.value }))} /></label></div><button className="button primary submit" type="submit">冻进我的雪糕柜</button></form></section>;
}
