import { useRef, useState } from "react";
import { recognizeTicket } from "../lib/ticketOcr.js";
import { addTripRecord } from "../lib/tripStore.js";

const empty = { city: "", region: "", date: "", days: 1, longitude: "", latitude: "", ticketType: "", ticketNumber: "" };
export default function TicketScanner({ onSaved }) {
  const inputRef = useRef(null); const [preview, setPreview] = useState(""); const [result, setResult] = useState(null); const [form, setForm] = useState(empty); const [status, setStatus] = useState("");
  const update = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  const choose = async (event) => { const file = event.target.files?.[0]; if (!file) return; setPreview(URL.createObjectURL(file)); setResult(null); setStatus("正在准备本地识别…"); try { const parsed = await recognizeTicket(file, setStatus); setResult(parsed); setForm((value) => ({ ...value, city: parsed.arrival, date: parsed.date, ticketType: parsed.type, ticketNumber: parsed.ticketNumber })); setStatus(parsed.arrival ? "已识别。请核对并补充坐标后保存。" : "未能可靠提取地点，请手动填写后保存。"); } catch { setStatus("识别失败，请更换清晰截图或改为手动录入。"); } event.target.value = ""; };
  const save = (event) => { event.preventDefault(); try { onSaved(addTripRecord(form)); setStatus("行程已保存到本地足迹。"); setResult(null); setPreview(""); setForm(empty); } catch (error) { setStatus(error.message); } };
  return <section className="scanner"><div className="collector-intro"><p className="eyebrow">LOCAL OCR</p><h2>扫描车票或机票</h2><p>截图只在当前设备浏览器内识别，不会上传。请遮挡姓名、证件号和订单号。</p></div><button className="scan-drop" onClick={() => inputRef.current?.click()}><span>＋</span><strong>选择票据截图</strong><small>支持相册或相机拍摄的 PNG、JPG、WEBP</small></button><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" capture="environment" hidden onChange={choose} />{preview && <img className="ticket-preview" src={preview} alt="待识别票据截图" />}{status && <p className="form-message" role="status">{status}</p>}{result && <details className="ocr-text"><summary>查看识别文本</summary><p>{result.rawText || "未识别到可读文字"}</p></details>}<form onSubmit={save} className="ocr-form"><div className="form-grid"><label>票据类型<input name="ticketType" value={form.ticketType} onChange={update} placeholder="机票或火车票" /></label><label>航班 / 车次<input name="ticketNumber" value={form.ticketNumber} onChange={update} placeholder="例如 CA1234" /></label></div><label>目的地（保存为足迹）<input name="city" value={form.city} onChange={update} placeholder="例如：示例城市甲" maxLength="30" /></label><label>区域名称<input name="region" value={form.region} onChange={update} placeholder="可选，例如：示例区域一" maxLength="30" /></label><div className="form-grid"><label>日期<input name="date" type="date" value={form.date} onChange={update} /></label><label>停留天数<input name="days" type="number" min="1" max="365" value={form.days} onChange={update} /></label></div><div className="form-grid"><label>经度<input name="longitude" type="number" step="0.0001" value={form.longitude} onChange={update} placeholder="例如：118.0000" /></label><label>纬度<input name="latitude" type="number" step="0.0001" value={form.latitude} onChange={update} placeholder="例如：32.0000" /></label></div><button className="button primary submit" type="submit">核对后保存足迹</button></form></section>;
}
