import { lazy, Suspense, useEffect, useRef, useState } from "react";
import { addRecord, exportRecords, importRecords, readRecords } from "../lib/tripStore.js";
import TicketScanner from "./TicketScanner.jsx";
import InstallApp from "../components/InstallApp.jsx";
import Onboarding from "../components/Onboarding.jsx";
import "../index.css";

const MapDashboard = lazy(() => import("./MapDashboard.jsx"));
const emptyForm = { city: "", region: "", date: new Date().toISOString().slice(0, 10), days: 1, longitude: "", latitude: "" };
function download(filename, text) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "application/json" })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }

function Collector({ onSaved }) { const [form, setForm] = useState(emptyForm); const [message, setMessage] = useState(""); const update = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value })); const submit = (event) => { event.preventDefault(); const { city, region, date, days, longitude, latitude } = form; if (!city.trim() || !region.trim() || !date || !Number(days) || longitude === "" || latitude === "") return setMessage("请把这一口旅程的信息填完整哦。"); if (Number(longitude) < 73 || Number(longitude) > 135 || Number(latitude) < 18 || Number(latitude) > 54) return setMessage("请填写中国大陆范围内的经纬度示例坐标。"); onSaved(addRecord(form)); setForm(emptyForm); setMessage("这段旅程已冻进雪糕里啦，回看板就能看到！"); }; return <section className="collector"><div className="collector-intro"><p className="eyebrow">SCOOP A MEMORY</p><h2>收进一口旅程</h2><p>把抵达过的地方，做成属于你的旅行雪糕球。</p></div><form onSubmit={submit}><label>这次去了哪里？<input name="city" value={form.city} onChange={update} placeholder="例如：郑州" maxLength="30" /></label><label>它属于哪一片？<input name="region" value={form.region} onChange={update} placeholder="例如：河南省" maxLength="30" /></label><div className="form-grid"><label>是哪一天？<input name="date" type="date" value={form.date} onChange={update} /></label><label>停留几天？<input name="days" type="number" min="1" max="365" value={form.days} onChange={update} /></label></div><div className="form-grid"><label>经度<input name="longitude" type="number" step="0.0001" value={form.longitude} onChange={update} placeholder="例如：118.0000" /></label><label>纬度<input name="latitude" type="number" step="0.0001" value={form.latitude} onChange={update} placeholder="例如：32.0000" /></label></div><button className="button primary submit" type="submit">冻进我的雪糕里</button>{message && <p className="form-message" role="status">{message}</p>}</form></section>; }

export default function TripMapDashboard() {
  const [route, setRoute] = useState(location.hash.slice(1) === "scan" ? "scan" : location.hash === "#collect" ? "collect" : "dashboard"); const [records, setRecords] = useState(readRecords); const [onboarded, setOnboarded] = useState(() => localStorage.getItem("xuegao.onboarded.v1") === "1"); const fileRef = useRef(null);
  useEffect(() => { const syncRoute = () => setRoute(location.hash.slice(1) === "scan" ? "scan" : location.hash === "#collect" ? "collect" : "dashboard"); const syncRecords = (event) => { if (event.key?.includes("local-footprint-map-demo")) setRecords(readRecords()); }; addEventListener("hashchange", syncRoute); addEventListener("storage", syncRecords); return () => { removeEventListener("hashchange", syncRoute); removeEventListener("storage", syncRecords); }; }, []);
  const switchRoute = (next) => { location.hash = next === "dashboard" ? "dashboard" : next; };
  const finishOnboarding = (next = "dashboard") => { localStorage.setItem("xuegao.onboarded.v1", "1"); setOnboarded(true); switchRoute(next); };
  const handleImport = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setRecords(importRecords(await file.text())); alert("旅行碎片已安全合并进雪糕柜。"); } catch { alert("无法导入：请选择由雪糕足迹导出的有效 JSON 文件。"); } event.target.value = ""; };
  return <main className="app-shell"><header className="topbar"><a className="brand" href="#dashboard" onClick={() => switchRoute("dashboard")}>雪糕<span>足迹</span></a><nav><button className={route === "dashboard" ? "nav-active" : ""} onClick={() => switchRoute("dashboard")}>雪糕柜</button><button className={route === "collect" ? "nav-active" : ""} onClick={() => switchRoute("collect")}>加一球</button><button className={route === "scan" ? "nav-active" : ""} onClick={() => switchRoute("scan")}>扫票据</button></nav><InstallApp /></header>{route === "dashboard" ? <><header className="page-heading"><p>ONE SCOOP, ONE STORY</p><h1>{records.length ? "今天，想回味哪段旅程？" : "从第一座城市开始吧"}</h1><span>{records.length ? "每抵达一个地方，就给雪糕柜添一球甜甜的回忆。" : "先逛逛城市图鉴，抵达后再把它收进你的雪糕柜。"}</span></header><Suspense fallback={<div className="map-wrap"><div className="status">正在打开雪糕地图…</div></div>}><MapDashboard records={records} onCollect={() => switchRoute("collect")} /></Suspense></> : route === "scan" ? <TicketScanner onSaved={setRecords} /> : <Collector onSaved={setRecords} />}<section className="sync-card"><div><p className="eyebrow">YOUR TRAVEL FREEZER</p><h2>旅行数据保存在这台设备</h2><p>不会每次重填；退出后仍会保留。登录同步功能将在安全后端接入后开启。</p></div><div className="sync-actions"><button className="button secondary" onClick={() => download("xuegao-travel.json", exportRecords())}>备份旅行碎片</button><button className="button secondary" onClick={() => fileRef.current?.click()}>导入旅行碎片</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={handleImport} /></div></section><footer>雪糕足迹 · 你的旅行数据默认只保存在当前设备</footer>{!onboarded && <Onboarding onDone={finishOnboarding} />}</main>;
}
