import { lazy, Suspense, useEffect, useRef, useState } from "react";
import { ORIGIN, addRecord, exportRecords, importRecords, readRecords, resetRecords } from "../lib/tripStore.js";
import TicketScanner from "./TicketScanner.jsx";
import InstallApp from "../components/InstallApp.jsx";
import "../index.css";
const MapDashboard = lazy(() => import("./MapDashboard.jsx"));
const emptyForm = { city: "", region: "", date: new Date().toISOString().slice(0, 10), days: 1, longitude: "", latitude: "" };

function download(filename, text) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "application/json" })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
function Collector({ onSaved }) { const [form, setForm] = useState(emptyForm); const [message, setMessage] = useState(""); const update = (e) => setForm((v) => ({ ...v, [e.target.name]: e.target.value })); const submit = (e) => { e.preventDefault(); const { city, region, date, days, longitude, latitude } = form; if (!city.trim() || !region.trim() || !date || !Number(days) || longitude === "" || latitude === "") return setMessage("请完整填写地点、日期、天数和坐标。"); if (Number(longitude) < 73 || Number(longitude) > 135 || Number(latitude) < 18 || Number(latitude) > 54) return setMessage("请填写中国大陆范围内的经纬度示例坐标。"); onSaved(addRecord(form)); setForm(emptyForm); setMessage("已保存。这台设备的网页看板会立即更新；跨设备请使用数据同步。"); }; return <section className="collector"><div className="collector-intro"><p className="eyebrow">MOBILE COLLECTION</p><h2>收集一段足迹</h2><p>仅录入公开或测试数据。提交后会保存到当前浏览器。</p></div><form onSubmit={submit}><label>地点名称<input name="city" value={form.city} onChange={update} placeholder="例如：示例城市庚" maxLength="30" /></label><label>区域名称<input name="region" value={form.region} onChange={update} placeholder="例如：示例区域七" maxLength="30" /></label><div className="form-grid"><label>到访日期<input name="date" type="date" value={form.date} onChange={update} /></label><label>停留天数<input name="days" type="number" min="1" max="365" value={form.days} onChange={update} /></label></div><div className="form-grid"><label>经度<input name="longitude" type="number" step="0.0001" value={form.longitude} onChange={update} placeholder="例如：118.0000" /></label><label>纬度<input name="latitude" type="number" step="0.0001" value={form.latitude} onChange={update} placeholder="例如：32.0000" /></label></div><button className="button primary submit" type="submit">保存这条记录</button>{message && <p className="form-message" role="status">{message}</p>}</form></section>; }
export default function TripMapDashboard() { const [route, setRoute] = useState(location.hash.slice(1) === "scan" ? "scan" : location.hash === "#collect" ? "collect" : "dashboard"); const [records, setRecords] = useState(readRecords); const fileRef = useRef(null); useEffect(() => { const syncRoute = () => setRoute(location.hash.slice(1) === "scan" ? "scan" : location.hash === "#collect" ? "collect" : "dashboard"); const syncRecords = (event) => { if (event.key?.includes("local-footprint-map-demo")) setRecords(readRecords()); }; addEventListener("hashchange", syncRoute); addEventListener("storage", syncRecords); return () => { removeEventListener("hashchange", syncRoute); removeEventListener("storage", syncRecords); }; }, []); const switchRoute = (next) => { location.hash = next === "dashboard" ? "dashboard" : next; }; const handleImport = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setRecords(importRecords(await file.text())); alert("数据已安全合并，看板已更新。"); } catch { alert("无法导入：请选择由本应用导出的有效 JSON 文件。"); } event.target.value = ""; }; return <main className="app-shell"><header className="topbar"><a className="brand" href="#dashboard" onClick={() => switchRoute("dashboard")}>足迹<span>·</span>本地</a><nav><button className={route === "dashboard" ? "nav-active" : ""} onClick={() => switchRoute("dashboard")}>看板</button><button className={route === "collect" ? "nav-active" : ""} onClick={() => switchRoute("collect")}>手动录入</button><button className={route === "scan" ? "nav-active" : ""} onClick={() => switchRoute("scan")}>票据识别</button></nav><InstallApp /></header>{route === "dashboard" ? <><header className="page-heading"><p>LOCAL DEMO · ANONYMIZED</p><h1>足迹回放</h1><span>手动录入或扫描票据，回来即可查看</span></header><Suspense fallback={<div className="map-wrap"><div className="status">正在准备地图…</div></div>}><MapDashboard records={records} /></Suspense></> : route === "scan" ? <TicketScanner onSaved={setRecords} /> : <Collector onSaved={setRecords} />}<section className="sync-card"><div><p className="eyebrow">DATA SYNC</p><h2>在另一台设备继续使用</h2><p>地图已支持离线查看；跨设备请导出后在另一台设备导入。</p></div><div className="sync-actions"><button className="button secondary" onClick={() => download("footprints-demo.json", exportRecords())}>导出数据</button><button className="button secondary" onClick={() => fileRef.current?.click()}>导入数据</button><button className="text-button" onClick={() => { if (confirm("将恢复为示例记录，当前本地数据会被替换。")) setRecords(resetRecords()); }}>恢复示例</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={handleImport} /></div></section><footer>本地脱敏演示数据 · 不含账户、云端存储或真实地点信息</footer></main>; }
