import { useEffect, useState } from "react";
import { syncAll } from "../lib/cloudSync.js";
import { cloudConfigured, supabase } from "../lib/supabaseClient.js";
import "./cloudAccount.css";

const friendlyError = (error) => error?.message?.includes("Invalid login") ? "邮箱或密码不正确。" : error?.message || "暂时无法连接云端，请稍后再试。";
const maskEmail = (email = "") => { const [name, domain] = email.split("@"); return name && domain ? `${name.slice(0, 2)}***@${domain}` : "当前账号"; };

export default function CloudAccount({ onSynced }) {
  const [session, setSession] = useState(null); const [mode, setMode] = useState("signin"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!cloudConfigured) return undefined; supabase.auth.getSession().then(({ data }) => setSession(data.session)).catch(() => setStatus("云端连接暂不可用。")); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); const failed = (event) => setStatus(`自动同步未完成：${event.detail || "请稍后点“立即同步”重试。"}`); addEventListener("xuegao:sync-error", failed); return () => { listener.subscription.unsubscribe(); removeEventListener("xuegao:sync-error", failed); }; }, []);
  const runSync = async () => { setBusy(true); setStatus("正在安全合并这台设备与云端的旅行记录…"); try { const result = await syncAll(); onSynced?.(result); setStatus("同步完成：本机与云端记录已经合并。 "); } catch (error) { setStatus(`同步未完成：${friendlyError(error)}`); } finally { setBusy(false); } };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setStatus(""); try { const action = mode === "signin" ? supabase.auth.signInWithPassword({ email, password }) : supabase.auth.signUp({ email, password }); const { data, error } = await action; if (error) throw error; if (data.session) { setSession(data.session); setStatus("登录成功，正在合并旅行记录…"); const result = await syncAll(); onSynced?.(result); setStatus("同步完成：旅行记录已安全合并。 "); } else setStatus("注册成功。请完成邮箱验证后，用此邮箱和密码登录同步。 "); } catch (error) { setStatus(friendlyError(error)); } finally { setBusy(false); } };
  const signOut = async () => { setBusy(true); try { const { error } = await supabase.auth.signOut(); if (error) throw error; setSession(null); setStatus("已退出账号；本机旅行记录仍保留在这台设备。 "); } catch (error) { setStatus(friendlyError(error)); } finally { setBusy(false); } };
  if (!cloudConfigured) return <section className="cloud-account"><div><p className="eyebrow">CLOUD BACKUP</p><h2>云同步准备中</h2><p>本机模式可正常使用。部署环境配置完成后，会在这里开放登录与跨设备同步。</p></div></section>;
  if (session) return <section className="cloud-account"><div><p className="eyebrow">CLOUD BACKUP</p><h2>已登录云端雪糕柜</h2><p>{maskEmail(session.user.email)} · 登录后会合并本机和云端记录，不覆盖任何一边。</p></div><div className="cloud-actions"><button className="button secondary" disabled={busy} onClick={runSync}>{busy ? "同步中…" : "立即同步"}</button><button className="text-button" disabled={busy} onClick={signOut}>退出登录</button></div>{status && <p className="cloud-status" role="status">{status}</p>}</section>;
  return <section className="cloud-account"><div><p className="eyebrow">CLOUD BACKUP</p><h2>登录后，跨设备保存旅行</h2><p>不登录也能完整使用；登录只同步已确认的旅行和计划，不上传截图或 OCR 原文。</p></div><form className="cloud-form" onSubmit={submit}><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="邮箱" autoComplete="email" required /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="至少 6 位密码" autoComplete={mode === "signin" ? "current-password" : "new-password"} minLength="6" required /><button className="button secondary" disabled={busy} type="submit">{busy ? "请稍候…" : mode === "signin" ? "登录并同步" : "注册账号"}</button><button className="text-button" type="button" onClick={() => { setMode(mode === "signin" ? "signup" : "signin"); setStatus(""); }}>{mode === "signin" ? "没有账号？注册" : "已有账号？登录"}</button></form>{status && <p className="cloud-status" role="status">{status}</p>}</section>;
}
