import { useState } from "react";
import { BUDGETS, CHECKLIST, PLAN_TEMPLATES } from "../lib/planTemplates.js";
import { planForCity, savePlan } from "../lib/planStore.js";
import "./tripPlan.css";
import "./planExtras.css";

export default function TripPlanCard({ city, guide, onBack }) {
  const template = PLAN_TEMPLATES[city]; const [plan, setPlan] = useState(() => planForCity(city) || { city, budget: "balanced", checks: {}, sources: {}, travelers: 1 });
  if (!template) return <div className="plan-empty"><span>🗓️</span><p>这座城市的计划模板还在准备中。</p><button className="button secondary" onClick={onBack}>返回城市卡</button></div>;
  const change = (next) => { setPlan(next); savePlan(next); }; const travelers = Math.max(1, Number(plan.travelers) || 1); const budget = BUDGETS.find((item) => item.id === plan.budget) || BUDGETS[1];
  return <div className="trip-plan"><button className="text-button" onClick={onBack}>← 返回城市卡</button><p className="eyebrow">TRIP PLAN · LOCAL FIRST</p><h2>{city}，先把旅行想明白</h2><section><h3>三个关键判断</h3>{template.decisions.map((item, i) => <p className="decision" key={item}><b>{i + 1}</b>{item}</p>)}</section><section><h3>按天安排</h3>{template.days.map((day, i) => <div className="plan-day" key={i}><b>DAY {i + 1}</b><span>{day.join(" · ")}</span></div>)}</section><section><h3>预算与 AA</h3><label className="traveler-count">同行人数<input type="number" min="1" max="99" value={travelers} onChange={(event) => change({ ...plan, travelers: event.target.value })} /><span>人</span></label><div className="budget-options">{BUDGETS.map((item) => <button key={item.id} className={plan.budget === item.id ? "is-selected" : ""} onClick={() => change({ ...plan, budget: item.id })}><b>{item.label}</b><span>¥{item.min.toLocaleString()}–{item.max.toLocaleString()} / 人</span><small>{item.note}</small></button>)}</div><p className="aa-total">预计总预算 ¥{(budget.min * travelers).toLocaleString()}–{(budget.max * travelers).toLocaleString()} · 均摊参考 ¥{budget.min.toLocaleString()}–{budget.max.toLocaleString()} / 人</p><p className="plan-note">这是按人均估算的 AA 参考，不代表已付款或实时价格；实际支出请以同行人确认结果为准。</p></section><section><h3>出发前确认</h3>{CHECKLIST.map((item) => <label className="plan-check" key={item}><input type="checkbox" checked={Boolean(plan.checks[item])} onChange={() => change({ ...plan, checks: { ...plan.checks, [item]: !plan.checks[item] } })} />{item}</label>)}<a href={guide.source.url} target="_blank" rel="noreferrer">打开官方信息核验 ↗</a><label className="plan-check"><input type="checkbox" checked={Boolean(plan.sources?.official)} onChange={() => change({ ...plan, sources: { ...plan.sources, official: !plan.sources?.official } })} />我已查看并自行确认官方信息</label></section><p className="plan-saved">已自动保存在这台设备</p></div>;
}
